//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessSet
    {
        public BusinessSet()
        {
            this.CouponSet = new HashSet<CouponSet>();
        }
    
        public int BusinessId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public int Category { get; set; }
        public string Phone { get; set; }
        public int AdminId { get; set; }
        public int BusinessOwnerId { get; set; }
    
        public virtual PersonSet_Admin PersonSet_Admin { get; set; }
        public virtual ICollection<CouponSet> CouponSet { get; set; }
        public virtual PersonSet_BusinessOwner PersonSet_BusinessOwner { get; set; }
    }
}
