//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponSet
    {
        public CouponSet()
        {
            this.OrderedCouponSet = new HashSet<OrderedCouponSet>();
            this.PersonSet_Customer = new HashSet<PersonSet_Customer>();
        }
    
        public int Name { get; set; }
        public int Category { get; set; }
        public int OriginalPrice { get; set; }
        public int DiscountPrice { get; set; }
        public string Description { get; set; }
        public int CouponCode { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public double AverageRank { get; set; }
        public int BusinessBusinessId { get; set; }
        public double CouponLocation_Coupon_x { get; set; }
        public string CouponLocation_Coupon_y { get; set; }
    
        public virtual BusinessSet BusinessSet { get; set; }
        public virtual LocationSet LocationSet { get; set; }
        public virtual ICollection<OrderedCouponSet> OrderedCouponSet { get; set; }
        public virtual CouponSet_SocailNetworkCoupon CouponSet_SocailNetworkCoupon { get; set; }
        public virtual ICollection<PersonSet_Customer> PersonSet_Customer { get; set; }
    }
}
