//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationSet
    {
        public LocationSet()
        {
            this.CouponSet = new HashSet<CouponSet>();
            this.PersonSet_Customer = new HashSet<PersonSet_Customer>();
        }
    
        public double x { get; set; }
        public string y { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<CouponSet> CouponSet { get; set; }
        public virtual ICollection<PersonSet_Customer> PersonSet_Customer { get; set; }
    }
}
