//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSet_Customer
    {
        public PersonSet_Customer()
        {
            this.OrderedCouponSet = new HashSet<OrderedCouponSet>();
            this.CouponSet = new HashSet<CouponSet>();
            this.CouponSet_SocailNetworkCoupon = new HashSet<CouponSet_SocailNetworkCoupon>();
        }
    
        public int Id { get; set; }
        public double CustomerLocation_Customer_x { get; set; }
        public string CustomerLocation_Customer_y { get; set; }
    
        public virtual LocationSet LocationSet { get; set; }
        public virtual ICollection<OrderedCouponSet> OrderedCouponSet { get; set; }
        public virtual PersonSet PersonSet { get; set; }
        public virtual ICollection<CouponSet> CouponSet { get; set; }
        public virtual ICollection<CouponSet_SocailNetworkCoupon> CouponSet_SocailNetworkCoupon { get; set; }
    }
}
