//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSet_Admin
    {
        public PersonSet_Admin()
        {
            this.BusinessSet = new HashSet<BusinessSet>();
            this.CouponSet_SocailNetworkCoupon = new HashSet<CouponSet_SocailNetworkCoupon>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<BusinessSet> BusinessSet { get; set; }
        public virtual ICollection<CouponSet_SocailNetworkCoupon> CouponSet_SocailNetworkCoupon { get; set; }
        public virtual PersonSet PersonSet { get; set; }
    }
}
