//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSet
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Age { get; set; }
        public string Sex { get; set; }
    
        public virtual PersonSet_Admin PersonSet_Admin { get; set; }
        public virtual PersonSet_BusinessOwner PersonSet_BusinessOwner { get; set; }
        public virtual PersonSet_Customer PersonSet_Customer { get; set; }
    }
}
