//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CouponModelContainer : DbContext
    {
        public CouponModelContainer()
            : base("name=CouponModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Person> PersonSet { get; set; }
        public DbSet<OrderedCoupon> OrderedCouponSet { get; set; }
        public DbSet<Coupon> CouponSet { get; set; }
        public DbSet<Location> LocationSet { get; set; }
        public DbSet<Business> BusinessSet { get; set; }
    }
}
