//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.Customer1 = new HashSet<Customer>();
            this.OrderedCoupon = new HashSet<OrderedCoupon>();
        }
    
        public string Name { get; set; }
        public Nullable<CategoryType> Category { get; set; }
        public Nullable<int> OriginalPrice { get; set; }
        public Nullable<int> DiscountPrice { get; set; }
        public string Description { get; set; }
        public Nullable<int> CouponCode { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<double> AverageRank { get; set; }
    
        public virtual ICollection<Customer> Customer1 { get; set; }
        public virtual ICollection<OrderedCoupon> OrderedCoupon { get; set; }
        public virtual Location Location { get; set; }
        public virtual Business Business { get; set; }
    }
}
