//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer : Person
    {
        public Customer()
        {
            this.SocailNetworkCoupon = new HashSet<SocailNetworkCoupon>();
            this.OrderedCoupon = new HashSet<OrderedCoupon>();
            this.Coupon = new HashSet<Coupon>();
        }
    
        public string LocationAddress { get; set; }
    
        public virtual ICollection<SocailNetworkCoupon> SocailNetworkCoupon { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<OrderedCoupon> OrderedCoupon { get; set; }
        public virtual ICollection<Coupon> Coupon { get; set; }
    }
}
