//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Customer = new HashSet<Customer>();
            this.Coupon = new HashSet<Coupon>();
        }
    
        public Nullable<double> x { get; set; }
        public string y { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Coupon> Coupon { get; set; }
    }
}
