//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedCoupon
    {
        public string CouponId { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<int> Rank { get; set; }
        public string CouponName { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Coupon Coupon { get; set; }
    }
}
