//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocailNetworkCoupon : Coupon
    {
        public SocailNetworkCoupon()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public string SocialWebsite { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual Admin Admin { get; set; }
    }
}
